new config searching path
flavio/kuberlr pull request #79
Opened 2024-03-19 08:57 UTC by gzm55

fix #78

2024-05-17 00:50 UTC, gzm55 commented
@flavio could u plz review this pr?

2024-10-05 15:27 UTC, gzm55 commented
@flavio `$KUBERLR_CFG` is ready here

2024-10-07 06:43 UTC, flavio requested changes
Overall LGTM, I left some comments.

Please update also the README to mention the new environment variable.

2024-10-07 06:43 UTC, flavio commented on internal/config/config.go
>  func mergeConfig(v *viper.Viper, extraConfigPath string) error {
Please rename `extraConfigPath` to `cfgFile`

2024-10-07 06:43 UTC, flavio commented on internal/config/config.go
> +	}
This can be dropped when get `cfgFile` as input parameter

2024-10-07 06:43 UTC, flavio commented on internal/config/config_test.go
Can you add a new unit test that covers the env variable case?

2024-10-07 06:43 UTC, flavio commented on internal/config/paths_unix.go
>  var configPaths = []string{ //nolint: gochecknoglobals // arrays cannot be go constants
nit, rename it to `configFiles`, these are no longer paths.

2024-10-07 06:43 UTC, flavio commented on internal/config/paths_windows.go
>  var configPaths = []string{
nit, rename it to `configFiles`, these are no longer paths.

2024-10-07 07:54 UTC, gzm55 commented on internal/config/config_test.go
append an empty string to path array in `TestMergeConfigs` to test the case when the KUBERLR_CFG is unset.

2024-10-07 07:56 UTC, gzm55 commented
> Overall LGTM, I left some comments.
> 
> Please update also the README to mention the new environment variable.

@flavio new env is listed in the README

2024-10-14 03:03 UTC, gzm55 commented
@flavio any suggestion on this pr?

2024-10-14 15:06 UTC, flavio approved these changes
Sorry for the late response, it has been a busy week

2024-10-14 15:06 UTC, merged